// Code generated by kod struct2interface; DO NOT EDIT.

package store

// DiskStore is a component that implements IKodComponent.
type IKodComponent interface {
	Get(string) any
	Set(string, any) error
}

// MemoryStore is a component that implements IKodComponent.
type IKodComponent interface {
	Get(string) any
	Set(string, any) error
}
